UPPERCASE_CHARACTER = 'U'
LOWERCASE_CHARACTER = 'L'
SPECIAL_CHARACTER = 'S'
NUMERICAL_CHARACTER = "N"
DEFAULT_PASSWORD_SIZE = 7

UPPERCASE_CHARACTER_ASCII_CODE_UPPER_LIMIT = 90
UPPERCASE_CHARACTER_ASCII_CODE_LOWER_LIMIT = 65

LOWERCASE_CHARACTER_ASCII_CODE_UPPER_LIMIT = 122
LOWERCASE_CHARACTER_ASCII_CODE_LOWER_LIMIT = 97

SPECIAL_CHARACTER_ASCII_CODE_UPPER_LIMIT = 47
SPECIAL_CHARACTER_ASCII_CODE_LOWER_LIMIT = 33

NUMERICAL_CHARACTER_ASCII_CODE_UPPER_LIMIT = 57
NUMERICAL_CHARACTER_ASCII_CODE_LOWER_LIMIT = 48
